import { MenuLayout, MenuComponent } from '../types';

const COLOR_MAP: Record<string, string> = {
  'cyan': '36',
  'magenta': '35',
  'green': '32',
  'yellow': '33',
  'red': '31',
  'blue': '34',
  'white': '37',
  'black': '30',
  'bright-cyan': '96',
  'bright-magenta': '95',
  'bright-green': '92',
  'bright-yellow': '93',
  'bright-red': '91',
  'bright-blue': '94',
  'bright-white': '97',
};

export function generateBashScript(layout: MenuLayout): string {
  let script = `#!/bin/bash

# Generated by Shell Menu Studio
# Name: ${layout.name}

# Function to move cursor and print
# Usage: draw_at y x "text" "color_code" "bold(0/1)"
draw_at() {
  local y=$1
  local x=$2
  local text="$3"
  local color=$4
  local bold=$5
  
  tput cup $y $x
  if [ "$bold" -eq 1 ]; then
    echo -e "\\e[1;\${color}m\${text}\\e[0m"
  else
    echo -e "\\e[\${color}m\${text}\\e[0m"
  fi
}

# Clear screen
clear
tput civis # Hide cursor

# Draw components
`;

  layout.components.forEach((comp) => {
    const colorCode = COLOR_MAP[comp.color] || '37';
    const boldBit = comp.bold ? '1' : '0';
    
    script += `\n# Component: ${comp.name}\n`;
    comp.content.forEach((line, index) => {
      // Escape double quotes and backslashes for the echo command
      const escapedLine = line.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
      script += `draw_at ${comp.y + index} ${comp.x} "${escapedLine}" "${colorCode}" "${boldBit}"\n`;
    });
  });

  script += `
# Wait for input
tput cup $(tput lines) 0
echo -e "\\n\\e[90mPress any key to exit...\\e[0m"
read -n 1 -s

# Cleanup
tput cnorm # Show cursor
clear
`;

  return script;
}
